CREATE OR REPLACE PROCEDURE P_USER_VALIDATE ( uname IN VARCHAR2, upwd IN VARCHAR2, ustatus OUT VARCHAR2 )
AS
v_cnt NUMBER;
BEGIN
SELECT COUNT(*) INTO v_cnt FROM USER_TABLE WHERE USERNAME = uname AND USERPWD = upwd ;
IF v_cnt = 1 THEN
ustatus := ' LOGIN SUCCESSFULL';
ELSE
USTATUS := 'LOGIN UNSUCCESS';
END IF;
END;






CREATE TABLE USER_TABLE (
USERNAME VARCHAR2(20),
USERPWD VARCHAR2(20)
);


INSERT INTO USER_TABLE (USERNAME,USERPWD) VALUES ('venkat2','12356');
commit;